### ISSUE TITLE
Instalação do MRTG

### ISSUE THREAD

**Issue by hnpjunior** [Sci-Fi/scifi#2]
Olá pessoal,

O MRTG está fazendo todo o processo de instalação automaticamente ao escolher o item 11.1) Install MRTG.

Ele instala e automaticamente vai passando todos os sub-itens da instalação automaticamente. Segue abaixo o log da instalação do MRTG
# 

MRTG

1
#1 Install MRTG

yum install mrtg php -y
++ yum install mrtg php -y
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
- base: mirror.globo.com
- epel: mirror.globo.com
- extras: mirror.globo.com
- updates: mirror.globo.com
  Setting up Install Process
  Resolving Dependencies
  --> Running transaction check
  ---> Package mrtg.x86_64 0:2.16.2-7.el6 will be installed
  --> Processing Dependency: mrtg-libs = 2.16.2-7.el6 for package: mrtg-2.16.2-7.el6.x86_64
  --> Processing Dependency: perl-Socket6 for package: mrtg-2.16.2-7.el6.x86_64
  --> Processing Dependency: perl-IO-Socket-INET6 for package: mrtg-2.16.2-7.el6.x86_64
  --> Processing Dependency: perl(locales_mrtg) for package: mrtg-2.16.2-7.el6.x86_64
  --> Processing Dependency: perl(MRTG_lib) for package: mrtg-2.16.2-7.el6.x86_64
  --> Processing Dependency: gd for package: mrtg-2.16.2-7.el6.x86_64
  --> Processing Dependency: libgd.so.2()(64bit) for package: mrtg-2.16.2-7.el6.x86_64
  ---> Package php.x86_64 0:5.3.3-27.el6_5 will be installed
  --> Processing Dependency: php-common(x86-64) = 5.3.3-27.el6_5 for package: php-5.3.3-27.el6_5.x86_64
  --> Processing Dependency: php-cli(x86-64) = 5.3.3-27.el6_5 for package: php-5.3.3-27.el6_5.x86_64
  --> Running transaction check
  ---> Package gd.x86_64 0:2.0.35-11.el6 will be installed
  --> Processing Dependency: libXpm.so.4()(64bit) for package: gd-2.0.35-11.el6.x86_64
  ---> Package mrtg-libs.x86_64 0:2.16.2-7.el6 will be installed
  --> Processing Dependency: perl(SNMP_Session) for package: mrtg-libs-2.16.2-7.el6.x86_64
  --> Processing Dependency: perl(BER) for package: mrtg-libs-2.16.2-7.el6.x86_64
  ---> Package perl-IO-Socket-INET6.noarch 0:2.56-4.el6 will be installed
  ---> Package perl-Socket6.x86_64 0:0.23-4.el6 will be installed
  ---> Package php-cli.x86_64 0:5.3.3-27.el6_5 will be installed
  ---> Package php-common.x86_64 0:5.3.3-27.el6_5 will be installed
  --> Running transaction check
  ---> Package libXpm.x86_64 0:3.5.10-2.el6 will be installed
  ---> Package perl-SNMP_Session.noarch 0:1.12-4.el6 will be installed
  --> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package                   Arch        Version               Repository    Size

Installing:
 mrtg                      x86_64      2.16.2-7.el6          base         694 k
 php                       x86_64      5.3.3-27.el6_5        updates      1.1 M
Installing for dependencies:
 gd                        x86_64      2.0.35-11.el6         base         142 k
 libXpm                    x86_64      3.5.10-2.el6          base          51 k
 mrtg-libs                 x86_64      2.16.2-7.el6          base          95 k
 perl-IO-Socket-INET6      noarch      2.56-4.el6            base          17 k
 perl-SNMP_Session         noarch      1.12-4.el6            base          67 k
 perl-Socket6              x86_64      0.23-4.el6            base          27 k
 php-cli                   x86_64      5.3.3-27.el6_5        updates      2.2 M
 php-common                x86_64      5.3.3-27.el6_5        updates      525 k
# Transaction Summary

Install      10 Package(s)

Total download size: 4.9 M
Installed size: 16 M
Downloading Packages:
(1/10): gd-2.0.35-11.el6.x86_64.rpm                      | 142 kB     00:00  
(2/10): libXpm-3.5.10-2.el6.x86_64.rpm                   |  51 kB     00:00  
(3/10): mrtg-2.16.2-7.el6.x86_64.rpm                     | 694 kB     00:02  
(4/10): mrtg-libs-2.16.2-7.el6.x86_64.rpm                |  95 kB     00:00  
(5/10): perl-IO-Socket-INET6-2.56-4.el6.noarch.rpm       |  17 kB     00:00  
(6/10): perl-SNMP_Session-1.12-4.el6.noarch.rpm          |  67 kB     00:00  
(7/10): perl-Socket6-0.23-4.el6.x86_64.rpm               |  27 kB     00:00  
(8/10): php-5.3.3-27.el6_5.x86_64.rpm                    | 1.1 MB     00:08  
(9/10): php-cli-5.3.3-27.el6_5.x86_64.rpm                | 2.2 MB     00:09     
## (10/10): php-common-5.3.3-27.el6_5.x86_64.rpm            | 525 kB     00:03     

Total                                           158 kB/s | 4.9 MB     00:31  
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : php-common-5.3.3-27.el6_5.x86_64                            1/10 
  Installing : perl-Socket6-0.23-4.el6.x86_64                              2/10 
  Installing : perl-IO-Socket-INET6-2.56-4.el6.noarch                      3/10 
  Installing : php-cli-5.3.3-27.el6_5.x86_64                               4/10 
  Installing : libXpm-3.5.10-2.el6.x86_64                                  5/10 
  Installing : gd-2.0.35-11.el6.x86_64                                     6/10 
  Installing : perl-SNMP_Session-1.12-4.el6.noarch                         7/10 
  Installing : mrtg-libs-2.16.2-7.el6.x86_64                               8/10 
  Installing : mrtg-2.16.2-7.el6.x86_64                                    9/10 
  Installing : php-5.3.3-27.el6_5.x86_64                                  10/10 
  Verifying  : perl-Socket6-0.23-4.el6.x86_64                              1/10 
  Verifying  : php-cli-5.3.3-27.el6_5.x86_64                               2/10 
  Verifying  : perl-SNMP_Session-1.12-4.el6.noarch                         3/10 
  Verifying  : php-5.3.3-27.el6_5.x86_64                                   4/10 
  Verifying  : mrtg-2.16.2-7.el6.x86_64                                    5/10 
  Verifying  : libXpm-3.5.10-2.el6.x86_64                                  6/10 
  Verifying  : php-common-5.3.3-27.el6_5.x86_64                            7/10 
  Verifying  : mrtg-libs-2.16.2-7.el6.x86_64                               8/10 
  Verifying  : perl-IO-Socket-INET6-2.56-4.el6.noarch                      9/10 
  Verifying  : gd-2.0.35-11.el6.x86_64                                    10/10 

Installed:
  mrtg.x86_64 0:2.16.2-7.el6             php.x86_64 0:5.3.3-27.el6_5            

Dependency Installed:
  gd.x86_64 0:2.0.35-11.el6  
  libXpm.x86_64 0:3.5.10-2.el6  
  mrtg-libs.x86_64 0:2.16.2-7.el6  
  perl-IO-Socket-INET6.noarch 0:2.56-4.el6  
  perl-SNMP_Session.noarch 0:1.12-4.el6  
  perl-Socket6.x86_64 0:0.23-4.el6  
  php-cli.x86_64 0:5.3.3-27.el6_5  
  php-common.x86_64 0:5.3.3-27.el6_5                                            

Complete!
#2 Copy Templates

mv /etc/mrtg /etc/mrtg.`date +%Y%m%d-%H%M%S`
date +%Y%m%d-%H%M%S
+++ date +%Y%m%d-%H%M%S
++ mv /etc/mrtg /etc/mrtg.20140626-071010
cp -pr $ModDir/MRTG/etcmrtg /etc/mrtg 
++ cp -pr /usr/share/scifi/install/modules//MRTG/etcmrtg /etc/mrtg
mv /var/www/mrtg /var/www/mrtg.`date +%Y%m%d-%H%M%S`
date +%Y%m%d-%H%M%S
+++ date +%Y%m%d-%H%M%S
++ mv /var/www/mrtg /var/www/mrtg.20140626-071011
cp -pr $ModDir/MRTG/varwwwmrtg /var/www/mrtg
++ cp -pr /usr/share/scifi/install/modules//MRTG/varwwwmrtg /var/www/mrtg
#3 Setup Cron

rm /etc/cron.d/mrtg
++ rm /etc/cron.d/mrtg
cp -p $ModDir/MRTG/mrtg.cron /etc/cron.d/mrtg
++ cp -p /usr/share/scifi/install/modules//MRTG/mrtg.cron /etc/cron.d/mrtg
#4 Setup Log

mkdir /var/log/mrtg
++ mkdir /var/log/mrtg
rm /etc/logrotate.d/mrtg 2>/dev/null
++ rm /etc/logrotate.d/mrtg
cp -p $ModDir/MRTG/mrtg.logrotate /etc/logrotate.d/mrtg
++ cp -p /usr/share/scifi/install/modules//MRTG/mrtg.logrotate /etc/logrotate.d/mrtg
#5 Setup MRTG in Apache

rm /etc/httpd/conf.d/mrtg.conf
++ rm /etc/httpd/conf.d/mrtg.conf
case "$MRTGAUTH" in
    [nN] )
      cp $ModDir/MRTG/mrtg.no.conf /etc/httpd/conf.d/mrtg.conf
      ;;
    [yY] )
      cp $ModDir/MRTG/mrtg.users.conf /etc/httpd/conf.d/mrtg.conf
      ;;
    [gG] )
      cp $ModDir/MRTG/mrtg.group.conf /etc/httpd/conf.d/mrtg.conf
      ;;
esac
++ case "$MRTGAUTH" in
++ cp /usr/share/scifi/install/modules//MRTG/mrtg.no.conf /etc/httpd/conf.d/mrtg.conf
sed -i s/LDAPSERVER/$LDAPSERVER/g /etc/httpd/conf.d/mrtg.conf
++ sed -i s/LDAPSERVER/127.0.0.1/g /etc/httpd/conf.d/mrtg.conf
sed -i s/LDAPSUFIX/$LDAPSUFIX/g /etc/httpd/conf.d/mrtg.conf
++ sed -i s/LDAPSUFIX/dc=uff,dc=br/g /etc/httpd/conf.d/mrtg.conf
sed -i s/MRTGGROUP/$MRTGGROUP/g /etc/httpd/conf.d/mrtg.conf
++ sed -i s/MRTGGROUP/NetAdmins/g /etc/httpd/conf.d/mrtg.conf
#6 Setup MRTG
# Subs
#7 Apache restart

service httpd restart
++ service httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
#8 Scripts

cp -f  $ModDir/MRTG/_.sh $SCRIPTDIR
++ cp -f /usr/share/scifi/install/modules//MRTG/incmrtg.sh /usr/share/scifi/install/modules//MRTG/incscifi.sh /usr/share/scifi/install/modules//MRTG/mdados.sh /usr/share/scifi/install/modules//MRTG/migraapdata.sh /usr/share/scifi/install/modules//MRTG/minimuda.sh /usr/share/scifi/install/modules//MRTG/muda.sh /usr/share/scifi/scripts/
ln -s $SCRIPTDIR/_.sh /usr/bin/ 2>/dev/null
++ ln -s /usr/share/scifi/scripts//fazbkp.sh /usr/share/scifi/scripts//incmrtg.sh /usr/share/scifi/scripts//incscifi.sh /usr/share/scifi/scripts//ldap.sh /usr/share/scifi/scripts//mdados.sh /usr/share/scifi/scripts//migraapdata.sh /usr/share/scifi/scripts//minimuda.sh /usr/share/scifi/scripts//muda.sh /usr/share/scifi/scripts//restauraLDAP.sh /usr/share/scifi/scripts//scifi-users.sh /usr/bin/

**Comment by CosmeFC** [comment]
Caro amigo,

olhei o report e não achei erro.
Tudo parece 100%, somo sempre é. ;-)

Abraços,
Cosme.

**Comment by helgadb** [comment]
Pode ser que o problema seja a numeração.  A pessoa acaba achando que deve
digitar o número para executar cada etapa.  Sugiro substituir por hífens
para evitar confusão.
Abs
Em 26/06/2014 11:16, "Cosme Faria Corrêa" notifications@github.com
escreveu:

Caro amigo,

olhei o report e não achei erro.
Tudo parece 100%, somo sempre é. ;-)

Abraços,
Cosme.

**Comment by hnpjunior** [comment]
Isso mesmo Helga, foi o que me aconteceu. 

Hermes

**Comment by CosmeFC** [comment]
Caros amigos,

estamos fechando nosso 1o issue no GH. :-)

**Comment by luizschara** [comment]
Vamos fechar quando os números forem trocados para algo neutro como hifen ou asterisco. Eu também pensei que tinha que digitar cada um dos números, em vez de só pressionar enter (isto é, a lista é informativa, e não a lista de passos que a pessoa vai seguir).

**Comment by hnpjunior** [comment]
Exatamente Luiz, concordo com sua sugestão.

Hermes

**Comment by CosmeFC** [comment]
Caros amigos,

esta é a tela.

   =========================================
   |           Easy Life for SCIFI         |
   =========================================
                 Apache Module

   This module will:
   1) Install Apache
   2) Start Apache

```
 Press <Enter> key
```

Será que algo assim poderia ser o suficiente?

   =========================================
   |           Easy Life for SCIFI         |
   =========================================
                 Apache Module

   This module will:
   1) Install Apache
   2) Start Apache
-    Press <Enter> key*_for continue_

Abraços,

On 6/26/2014 3:18 PM, Hermes Nunes Pereira Júnior wrote:

> Exatamente Luiz, concordo com sua sugestão.
> 
> Hermes
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Sci-Fi/scifi/issues/2#issuecomment-47267686.

## 

Cosme Corrêa
Universidade Federal Fluminense - UFF
Superintendência de Tecnologia da Informação - STI
+55 21 4042-6606

**Comment by luizschara** [comment]
Eu trocaria para o seguinte:

# 

# | Easy Life for SCIFI |

Apache Module

This module will:
- Install Apache
- Start Apache

Press <Enter> to continue

--schara

PS1: _to continue_

PS2: você pode trocar tudo usando sed

for d in 1 2 3 4 5 6 7 8 9 do; echo $d; sed s/d)/*/g arquivo; done

Um outro for com `cat lista` para os arquivos e troca os arquivos (se tiver
mais de 9 itens, aumentar a lista...)

2014-06-26 16:38 GMT-03:00 Cosme Faria Corrêa notifications@github.com:

**Comment by CosmeFC** [comment]
Feito.
